[package]
name = "beginning"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hello_macro = { path = "../beginning/hello_macro" }
hello_macro_derive = { path = "../beginning/hello_macro_derive" }